;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-char
        evil-delete-char
        evil-end-of-line
        evil-first-non-blank
        evil-force-normal-state
        evil-forward-char
        evil-insert
        evil-normal-state
        smex
        ))

(setq mc/cmds-to-run-once
      '(
        evil-goto-first-line
        evil-goto-line
        evil-next-line
        evil-previous-line
        evil-scroll-page-down
        ))
