(require 'setup-package)

;; install extensions if they're missing
(defun init--install-packages ()
  (packages-install
   (cons 'ace-jump-mode melpa)
   (cons 'ack gnu)
   (cons 'auctex gnu)
   (cons 'auto-complete melpa)
   (cons 'auto-complete-clang melpa)
   (cons 'android-mode melpa)
   (cons 'browse-kill-ring melpa)
   (cons 'company melpa)
   (cons 'dired+ melpa)
   (cons 'dired-details melpa)
   (cons 'dired-details+ melpa)
   (cons 'dired-single melpa)
   (cons 'dynamic-fonts melpa)
   (cons 'ecb melpa)
   (cons 'emacs-eclim melpa)
   (cons 'erc-hl-nicks melpa)
   (cons 'evil melpa)
   (cons 'evil-leader melpa)
   (cons 'flymake melpa)
   (cons 'flymake-cursor melpa)
   (cons 'fuzzy melpa)
   (cons 'geiser marmalade)
   (cons 'ggtags gnu)
   (cons 'git-blame melpa)
   (cons 'git-commit-mode melpa)
   (cons 'git-gutter-fringe melpa)
   (cons 'gitconfig-mode melpa)
   (cons 'github-browse-file melpa)
   (cons 'gitignore-mode melpa)
   (cons 'helm melpa)
   (cons 'helm-ack melpa)
   (cons 'helm-gtags melpa)
   (cons 'ibuffer-vc melpa)
   (cons 'ido-hacks melpa)
   (cons 'ido-ubiquitous melpa)
   (cons 'magit melpa)
   (cons 'nlinum gnu)
   (cons 'openwith melpa)
   (cons 'pos-tip melpa)
   (cons 'quack marmalade)
   (cons 'rainbow-delimiters melpa)
   (cons 'savekill melpa)
   (cons 'scheme-complete melpa)
   (cons 'session melpa)
   (cons 'shell-pop melpa)
   (cons 'smex melpa)
   (cons 'smartparens melpa)
   (cons 'smooth-scrolling melpa)
   (cons 'solarized-theme melpa)
   (cons 'surround melpa)
   (cons 'switch-window melpa)
   (cons 'undo-tree melpa)
   (cons 'visual-regexp melpa)
   (cons 'w3m melpa)
   (cons 'yasnippet melpa)
   (cons 'yagist melpa)))

(condition-case nil
    (init--install-packages)
  (error
   (package-refresh-contents)
   (init--install-packages)))

(provide 'auto-install-packages)
