(require 'company)
;; The useful keybindins from https://github.com/tcrayford/emacs/blob/master/vendor/slime-company.el
(define-key company-active-map (kbd "\C-n") 'company-select-next)
(define-key company-active-map (kbd "\C-p") 'company-select-previous)
(define-key company-active-map (kbd "\C-d") 'company-show-doc-buffer)
(define-key company-active-map (kbd "\C-v") 'company-show-location)
(define-key company-active-map (kbd "<tab>") 'company-complete)
(define-key company-active-map (kbd "\C-g") '(lambda ()
                                               (interactive)
                                               (company-abort)))

(define-key company-active-map (kbd "<escape>") '(lambda ()
                                                   (interactive)
                                                   (company-abort)
                                                   (if (fboundp 'evil-normal-state)
                                                       (evil-normal-state))))
(provide 'setup-company)
