(require 'setup-cc-mode)
(require 'setup-scheme-mode)
(require 'setup-python-mode)
(require 'setup-web-mode)
(require 'setup-css-mode)
(require 'setup-ruby-mode)
(require 'setup-tex)
(require 'setup-pkgbuild-mode)

(provide 'setup-lng-init)
