(require 'setup-cc-mode)
(require 'setup-scheme-mode)
(require 'setup-python-mode)
(require 'setup-web-mode)
(require 'setup-css-mode)
(require 'setup-scss-mode)
(require 'setup-ruby-mode)
(require 'setup-tex)
(require 'setup-haskell)
(require 'setup-pkgbuild-mode)
(require 'setup-coffee-mode)
(require 'setup-js2-mode)
(require 'setup-go-mode)
(require 'setup-elisp)
(require 'setup-clojure)

(provide 'setup-lng-init)
